import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@radix-ui/themes/styles.css";
import {Theme, ThemePanel} from "@radix-ui/themes";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="jade">
          {children}
        </Theme>
      </body>
    </html>
  );
}
